# Generated by Django 2.2 on 2019-05-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.CharField(default='', max_length=100, verbose_name='评论目标'),
        ),
    ]
